name: MLflow CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check MLflow version
        run: pip show mlflow

      - name: Run training
        run: python train.py

      - name: Upload MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/

      - name: Validate model
        run: python validate.py

      - name: Drift detection
        run: python drift_check.py

      - name: Deploy (only if passed validation + drift)
        if: success()
        run: echo "🚀 Deploying model..."
